FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY *.js ./

ENV GITHUB_TOKEN= \
    GIST_ID= \
    GIST_FILENAME=ip.txt \
    GODADDY_HOST= \
    GODADDY_KEY= \
    GODADDY_SECRET= \
    UPDATE_FREQ=1h \
    DEBUG=dynip:*


CMD ["node", "index.js"]